### ISSUE TITLE
Set up auto-deployment with Travis

### ISSUE THREAD

**Issue by susutou** [handsdirty/handsdirty.github.io#26]
Hi @handsdirty, it's possible to set up auto-deployment via Travis, so that once you commit new changes  to the Hexo source files, a new version of static files will be automatically generated and deployed to your GitHub pages (v.s. generate locally and commit to your GitHub pages manually). See this [post](https://zespia.tw/blog/2015/01/21/continuous-deployment-to-github-with-travis/) for more details. You can also check my [repository](https://github.com/susutou/blog) for a working example. This feels more fun to me :smile:

**Comment by handsdirty** [comment]
Thanks a lot for helping me improving my blog.
Will do.

**Comment by handsdirty** [comment]
Won't fix.
A confusing and low-priority thing for me.
I will keep typing "hexo generate --deploy" :P
Thanks anyway.
