### ISSUE TITLE
父亲的两个故事与职场的发展

### ISSUE THREAD

**Issue by handsdirty** [handsdirty/handsdirty.github.io#9]

**Comment by wujie27** [comment]
Very interested in this one!

**Comment by handsdirty** [comment]
下一篇中文的就写它。昨天刚采访完我爸 :laughing:

**Comment by susutou** [comment]
:+1:

**Comment by handsdirty** [comment]
http://zhesong.info/2016/01/31/father-two-stories/
http://zhesong.info/2016/01/31/father-two-stories-en/

**Comment by wujie27** [comment]
很有启发。

**Comment by handsdirty** [comment]
棒。吴杰兄啥时候开博啊？

**Comment by wujie27** [comment]
最近没有灵感。。写不太出。哈哈，你有啥办法？

**Comment by handsdirty** [comment]
先把2015年终总结写了吧，再不写就再没机会写了

**Comment by wujie27** [comment]
Good idea!
